# Generated by Django 3.1.1 on 2020-11-16 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payingguest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Type of PG must be greater than 2 characters')])),
                ('location', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Location name must be greater than 2 characters')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('condition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PGFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payingguest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payingguest.payingguest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('payingguest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PGComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payingguest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payingguest.payingguest')),
            ],
        ),
        migrations.AddField(
            model_name='payingguest',
            name='comments',
            field=models.ManyToManyField(related_name='pgcomments_owned', through='payingguest.PGComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payingguest',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_payingguest', through='payingguest.PGFav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payingguest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
