# Generated by Django 3.1.1 on 2020-11-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payingguest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payingguest',
            old_name='name',
            new_name='City',
        ),
    ]
