# Generated by Django 3.1.1 on 2020-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payingguest', '0002_auto_20201116_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payingguest',
            old_name='price',
            new_name='rent',
        ),
        migrations.RemoveField(
            model_name='payingguest',
            name='location',
        ),
        migrations.AddField(
            model_name='payingguest',
            name='pgaddress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payingguest',
            name='useraddress',
            field=models.TextField(null=True),
        ),
    ]
