# Generated by Django 3.1.1 on 2020-11-17 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payingguest', '0003_auto_20201117_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payingguest',
            name='pgaddress',
        ),
        migrations.RemoveField(
            model_name='payingguest',
            name='useraddress',
        ),
        migrations.AddField(
            model_name='payingguest',
            name='pg_address',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Type of PG must be greater than 2 characters')]),
        ),
        migrations.AddField(
            model_name='payingguest',
            name='user_address',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Type of PG must be greater than 2 characters')]),
        ),
    ]
