# Generated by Django 3.1.1 on 2020-11-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201030_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
    ]
