# Generated by Django 3.1.1 on 2020-10-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201004_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fav',
            name='book',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
